[app]
# The name of your app as displayed in the menu
name = "EMF_Day"

# The submenu where your app should appear.
# One of: "Badge", "Music", "Media", "Apps", "Games"
category = "Badge"

# OPTIONAL: Same as above, for compatibility with older firmware
# versions that can't handle categories introduced afterwards.
# One of: "Badge", "Music", "Apps"
# menu = "Badge"

# OPTIONAL: If your app prefers wifi to be off or on when entering.
# Useful if you want more resources (false) or need wifi (true).
# Remove if you don't want to change wifi state!
wifi_preference = true

[entry]
# The name of your entry point `Application` class
class = "EMF_Day"

[metadata]
# Your nickname.  Must be at most 32 characters!
author = "MartinH"

# License of your app as an SPDX identifier: <https://spdx.org/licenses/>
license = "LGPL-3.0-only"

# URL to the repository of your app.
url = "https://github.com/martin-hamilton/EMF-DAY"

# Description of your app.  Maximum 140 characters!
description = "EMF never ended. Find out what day of the festival it is today."

# Version number of your app.  If you push a commit where this number is
# increased, we interpret this as a new version being released.
#
# Version number must be an integer!
version = "0.1.0"

